"""Generate S02 solo-agent bootstrap documentation.

The generator renders a compact, deterministic set of orientation documents
from :mod:`srl.labctl`. It supports ``--check`` so CI can detect drift without
rewriting files.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from srl.labctl import labctl_manifest

ROOT = Path(__file__).resolve().parents[2]


def _front_matter() -> str:
    return (
        "<!-- generated by scripts/docs/generate_solo_agent_docs.py; "
        "edit source data in srl.labctl -->\n\n"
    )


def _cell_rows() -> list[str]:
    manifest = labctl_manifest()
    rows = [
        "| Cell | Native bootstrap | Transport | Status |",
        "|---|---|---|---|",
    ]
    for cell in manifest["cells"]:
        rows.append(
            "| {display_name} | `{native_bootstrap}` | `{allowed_transport}` | `{status}` |".format(
                **cell
            )
        )
    return rows


def _authority_rows() -> list[str]:
    manifest = labctl_manifest()
    rows = ["| Field | Value |", "|---|---|"]
    for key, value in manifest["authority_invariants"].items():
        rendered = str(value).lower() if isinstance(value, bool) else str(value)
        rows.append(f"| `{key}` | `{rendered}` |")
    return rows


def _start_here() -> str:
    manifest = labctl_manifest()
    lines = [
        "# START-HERE",
        "",
        _front_matter().rstrip(),
        "Scientific Reasoning Fabric starts from one JSON-first entrypoint:",
        "",
        "```bash",
        manifest["entry_command"],
        "```",
        "",
        "A successful entry emits `LabCtlEnterReport/v1` with a scope-only",
        "`LabAccessReceipt/v1`. The receipt never grants authority, never",
        "permits live trading, and never permits target-specific security action.",
        "",
        "Minimum fresh-agent sequence:",
        "",
        "1. Run `srlab labctl enter`.",
        "2. Run `srlab doctor`.",
        "3. Inspect available capabilities with `srlab catalog inspect`.",
        "4. Build a request with `srlab plan build <bundle-file>`.",
        "5. Execute only bounded, admitted work with `srlab run execute <run-spec-file>`.",
        "",
    ]
    return "\n".join(lines)


def _system_atlas() -> str:
    lines = [
        "# SYSTEM-ATLAS",
        "",
        _front_matter().rstrip(),
        "SRF is a contract-first scientific computation fabric. It owns",
        "scientific computation, receipts, bounded execution, safe export packets",
        "and standalone documentation. It does not own Market authority, Security",
        "authority, paid credentials, target actions, or physical storage writes.",
        "",
        "## Cells",
        "",
        *_cell_rows(),
        "",
        "## Shared Nerves",
        "",
        "- Request: `ScientificRequestEnvelope/v1`.",
        "- Result: `ScientificResultEnvelope/v1`.",
        "- Receipt: `ScientificRunReceipt/v1` and import receipts.",
        "- Health: `SRFPulse/v1` plus read-only federation status.",
        "",
    ]
    return "\n".join(lines)


def _runbook() -> str:
    lines = [
        "# SOLO-AGENT-RUNBOOK",
        "",
        _front_matter().rstrip(),
        "A solo agent uses SRF by following receipts, not chat history.",
        "",
        "## Entry",
        "",
        "```bash",
        "srlab labctl enter",
        "srlab doctor",
        "srlab catalog inspect",
        "```",
        "",
        "## Request",
        "",
        "Prepare a JSON bundle containing one scientific request and one claim,",
        "then run `srlab plan build <bundle-file>`. If a capability is missing,",
        "the planner returns a typed WAIT state instead of selecting an unsafe",
        "fallback.",
        "",
        "## Execution",
        "",
        "Run bounded work with `srlab run execute <run-spec-file>`. Exit code `0`",
        "means a receipt was emitted. It does not validate the scientific claim.",
        "",
        "## Recovery",
        "",
        "Keep one writer, preserve evidence, retry only clear transients once,",
        "and park protected or unavailable capabilities with exact WAIT states.",
        "",
    ]
    return "\n".join(lines)


def _cell_matrix() -> str:
    lines = [
        "# CELL-MATRIX",
        "",
        _front_matter().rstrip(),
        *_cell_rows(),
        "",
        "Cross-lab cells are proposal-only until their native bootstrap and owner",
        "policy admit the corresponding child mission.",
        "",
    ]
    return "\n".join(lines)


def _authority_matrix() -> str:
    lines = [
        "# AUTHORITY-MATRIX",
        "",
        _front_matter().rstrip(),
        *_authority_rows(),
        "",
        "SRF results are evidence packets and proposals. They are never authority",
        "to trade, execute target-specific security actions, install credentials,",
        "spend paid budget, deploy services, reboot systems, or perform destructive",
        "storage operations.",
        "",
    ]
    return "\n".join(lines)


def render_docs() -> dict[Path, str]:
    """Return all generated S02 document paths and contents."""
    return {
        ROOT / "START-HERE.md": _start_here(),
        ROOT / "SYSTEM-ATLAS.md": _system_atlas(),
        ROOT / "SOLO-AGENT-RUNBOOK.md": _runbook(),
        ROOT / "CELL-MATRIX.md": _cell_matrix(),
        ROOT / "AUTHORITY-MATRIX.md": _authority_matrix(),
    }


def main(argv: list[str] | None = None) -> int:
    """Generate docs or check that generated docs are current."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    failures = 0
    for path, expected in render_docs().items():
        expected = expected if expected.endswith("\n") else expected + "\n"
        if args.check:
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != expected:
                failures += 1
                diff = difflib.unified_diff(
                    actual.splitlines(),
                    expected.splitlines(),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                    lineterm="",
                )
                sys.stdout.write("\n".join(diff) + "\n")
        else:
            path.write_text(expected, encoding="utf-8")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
