"""Generate S26 system documentation closure documents.

The generated files are compact root-level indices over machine-readable
project data and existing detailed docs. Use ``--check`` to detect drift without
rewriting files.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]


def _front_matter() -> str:
    return (
        "<!-- generated by scripts/docs/generate_system_docs.py; "
        "edit source manifests, schemas or detailed docs -->\n"
    )


def _json(path: str) -> dict[str, Any]:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def _h1(title: str) -> list[str]:
    return [f"# {title}", "", _front_matter()]


def _capability_catalog() -> str:
    catalog = _json("src/srl/planning/catalog_data.json")
    rows = [
        "| Profile | Capability id | Adapter | Availability |",
        "|---|---|---|---|",
    ]
    for item in catalog["capabilities"]:
        rows.append(
            "| `{profile}` | `{capability_id}` | `{adapter}` | `{availability}` |".format(
                profile=item["profile"],
                capability_id=item["capability_id"],
                adapter=item["adapter_id"] or "none",
                availability=item["availability"],
            )
        )
    lines = [
        *_h1("CAPABILITY-CATALOG"),
        "Machine source: `src/srl/planning/catalog_data.json`.",
        "Detailed docs: `docs/catalog/` and `docs/architecture/`.",
        "",
        *rows,
        "",
        "Policy: unavailable, future or remote-required capabilities return typed",
        "`WAIT_CAPABILITY` or `WAIT_REMOTE_EXECUTOR`; SRF must not silently route",
        "to an unrelated local substitute.",
        "",
    ]
    return "\n".join(lines)


def _contract_matrix() -> str:
    schema_dir = ROOT / "src/srl/contracts/schemas/v1"
    rows = ["| Schema | Contract |", "|---|---|"]
    for path in sorted(schema_dir.glob("*.json")):
        schema = json.loads(path.read_text(encoding="utf-8"))
        title = schema.get("title") or path.stem
        rows.append(f"| `{path.name}` | `{title}` |")
    lines = [
        *_h1("CONTRACT-MATRIX"),
        "Machine source: `src/srl/contracts/schemas/v1/`.",
        "Compatibility checks: `scripts/checks/schema-meta-validate.py` and",
        "`scripts/checks/schema-compat.py`.",
        "",
        *rows,
        "",
        "Contract changes that break published consumers require an explicit",
        "schema version bump and cannot be hidden inside documentation updates.",
        "",
    ]
    return "\n".join(lines)


def _data_classification() -> str:
    rows = [
        "| Class | Public repo handling |",
        "|---|---|",
        "| `D0` | Public docs, schemas, fixtures and proposal-safe examples. |",
        "| `D1` | Sanitized metadata and C3 proposal envelopes only. |",
        "| `D2` | Not committed; replace with public digest or typed WAIT. |",
        "| `D3` | Not committed, logged or exported. |",
    ]
    lines = [
        *_h1("DATA-CLASSIFICATION"),
        "Detailed sources: `docs/tutorials/boundaries.md`,",
        "`docs/operations/private-overlay.md`, and bridge schemas.",
        "",
        *rows,
        "",
        "Public export packets are review-only. They carry no credentials, no raw",
        "private paths, no private datasets, no trading strategy and no exploit",
        "material.",
        "",
    ]
    return "\n".join(lines)


def _failure_routing() -> str:
    registry = _json("automation/fail-reasons.json")
    by_class = Counter(item["class"] for item in registry["reasons"])
    rows = ["| Class | Registered reasons |", "|---|---|"]
    for name, count in sorted(by_class.items()):
        rows.append(f"| `{name}` | {count} |")
    wait_rows = ["| WAIT reason | Meaning |", "|---|---|"]
    for item in registry["reasons"]:
        if item["class"] == "wait":
            wait_rows.append(f"| `{item['id']}` | {item['description']} |")
    lines = [
        *_h1("FAILURE-ROUTING"),
        "Machine source: `automation/fail-reasons.json`.",
        "Detailed sources: `docs/operations/RECOVERY-RUNBOOK.md` and",
        "`docs/verification/SYSTEM-ACCEPTANCE.md`.",
        "",
        *rows,
        "",
        "## WAIT states",
        "",
        *wait_rows,
        "",
        "Failures are evidence. They are not approval to trade, deploy, restart,",
        "write protected storage or perform target-specific security work.",
        "",
    ]
    return "\n".join(lines)


def _t7_operations() -> str:
    lines = [
        *_h1("T7-OPERATIONS"),
        "Detailed sources: `docs/architecture/storage.md`,",
        "`docs/operations/t7-physical-profile.md`, and",
        "`docs/target-binding/t7-readonly-preflight.json`.",
        "",
        "- T7 is append-only cold recovery storage.",
        "- Active databases and WAL files must never be placed there.",
        "- Format, erase, restore, sync and destructive storage operations require",
        "  explicit native target authority.",
        "- Current SRF state records `WAIT_T7_BINDING`; software validation continues",
        "  independently while protected binding remains parked.",
        "",
    ]
    return "\n".join(lines)


def _compute_node() -> str:
    lines = [
        *_h1("COMPUTE-NODE"),
        "Detailed sources: `docs/operations/compute-node.md` and",
        "`docs/architecture/future-profiles.md`.",
        "",
        "Heavy capabilities route through signed remote job packets only when a",
        "compatible compute node, image digest, checkpoint interval and budget",
        "receipt are available. Missing node, architecture mismatch, revoked image",
        "or exhausted budget returns a typed WAIT/REJECT decision; SRF must not fall",
        "back to an unbounded local Mac run.",
        "",
        "Current state: `WAIT_COMPUTE_NODE`.",
        "",
        "A15 software readiness receipt:",
        "`docs/verification/srf-v3-7-a15-heavy-compute-wait-receipt.json`.",
        "",
        "Protected activation action:",
        "`docs/target-binding/a15-heavy-compute-operator-action.json`.",
        "",
    ]
    return "\n".join(lines)


def _market_integration() -> str:
    lines = [
        *_h1("MARKET-INTEGRATION"),
        "Detailed sources: `docs/integrations/MARKET-INTEGRATION.md`,",
        "`docs/integrations/MARKET-CHILD-MISSION.md`, and",
        "`docs/child-missions/market/`.",
        "",
        "The Market bridge is inactive and proposal-only. It imports sanitized C3",
        "observations only after native health is green and native policy admits the",
        "child lane. It rejects trading actions, orders, credentials, authority",
        "claims, duplicate imports and stale native HEAD bindings.",
        "",
        "Current state: `WAIT_RUNTIME_HEALTH:MARKET_RED_F8`.",
        "",
    ]
    return "\n".join(lines)


def _security_integration() -> str:
    lines = [
        *_h1("SECURITY-INTEGRATION"),
        "Detailed sources: `docs/integrations/SECURITY-INTEGRATION.md`,",
        "`docs/integrations/SECURITY-CHILD-MISSION.md`, and",
        "`docs/child-missions/security/`.",
        "",
        "The Security bridge is inactive and proposal-only. It accepts only",
        "sanitized D0/D1 C3 findings inside the declared boundary. It rejects target",
        "identifiers, exploit material, payloads, credentials, target actions,",
        "authority claims, duplicate imports and stale native HEAD bindings.",
        "",
        "Current state: `WAIT_SECURITY_HEALTH:BOOTSTRAP_UNAVAILABLE`.",
        "",
    ]
    return "\n".join(lines)


def _trading_boundary() -> str:
    lines = [
        *_h1("TRADING-EXECUTION-BOUNDARY"),
        "SRF is not a trading executor. SRF receipts, model outputs, validation",
        "runs, export packets and bridge messages are C3/proposal-only. They never",
        "authorize orders, live trading, portfolio mutation, credential use, paid",
        "API spend or Market runtime control.",
        "",
        "Market actions require the Market repository's native authority chain.",
        "SRF may prepare sanitized child mission packets and exact WAIT receipts;",
        "it may not bypass RED, branch protection or native runtime gates.",
        "",
    ]
    return "\n".join(lines)


def _pack_authoring() -> str:
    manifests = sorted((ROOT / "packs").glob("*/manifest.json"))
    rows = ["| Pack manifest |", "|---|"]
    rows.extend(f"| `{path.relative_to(ROOT)}` |" for path in manifests)
    lines = [
        *_h1("PACK-AUTHORING"),
        "Detailed sources: `docs/architecture/pack-manifest.md`,",
        "`docs/architecture/pack-admission.md`, and `docs/architecture/p1-admission.md`.",
        "",
        *rows,
        "",
        "A pack must bind source, lock, tree hash, license texts, probes, schemas,",
        "resource policy and rollback evidence. Probe success is not scientific",
        "truth; it is only admission evidence for bounded execution.",
        "",
    ]
    return "\n".join(lines)


def _pack_revocation() -> str:
    lines = [
        *_h1("PACK-REVOCATION"),
        "Detailed sources: `docs/architecture/pack-admission.md`,",
        "`tests/packs/test_governance.py`, and `tests/heavy/test_remote_routing.py`.",
        "",
        "Direct or transitive pack revocation outranks otherwise complete evidence.",
        "Remote image revocation rejects heavy jobs before launch. Revocation is a",
        "stop signal for the affected capability, not a reason to silently choose a",
        "different backend.",
        "",
    ]
    return "\n".join(lines)


def _recovery_runbook() -> str:
    lines = [
        *_h1("RECOVERY-RUNBOOK"),
        "Detailed source: `docs/operations/RECOVERY-RUNBOOK.md`.",
        "",
        "Recovery rules:",
        "",
        "1. Preserve evidence and exact failure signature.",
        "2. Retry an identical command only for a plausible transient failure.",
        "3. Try materially different recoveries before parking a lane.",
        "4. Park protected or unavailable capability with exact `WAIT_*` state.",
        "5. Continue independent safe stages.",
        "",
    ]
    return "\n".join(lines)


def _release_runbook() -> str:
    lines = [
        *_h1("RELEASE-RUNBOOK"),
        "Release preconditions:",
        "",
        "- SystemAcceptanceReceipt and DocumentationClosureReceipt are current.",
        "- Worktree is clean except planned release artifacts.",
        "- Public-boundary and secret scans are clean.",
        "- Candidate-specific checks, reproducibility checks and docs checks pass.",
        "- PR/merge/release follow repository-native governance.",
        "",
        "Release evidence must include main SHA, tag, artifact hashes, SBOM,",
        "public-boundary result, secret-scan result, release URL or exact native",
        "blocker, and MissionCloseoutReceipt.",
        "",
    ]
    return "\n".join(lines)


def render_docs() -> dict[Path, str]:
    return {
        ROOT / "CAPABILITY-CATALOG.md": _capability_catalog(),
        ROOT / "CONTRACT-MATRIX.md": _contract_matrix(),
        ROOT / "DATA-CLASSIFICATION.md": _data_classification(),
        ROOT / "FAILURE-ROUTING.md": _failure_routing(),
        ROOT / "T7-OPERATIONS.md": _t7_operations(),
        ROOT / "COMPUTE-NODE.md": _compute_node(),
        ROOT / "MARKET-INTEGRATION.md": _market_integration(),
        ROOT / "SECURITY-INTEGRATION.md": _security_integration(),
        ROOT / "TRADING-EXECUTION-BOUNDARY.md": _trading_boundary(),
        ROOT / "PACK-AUTHORING.md": _pack_authoring(),
        ROOT / "PACK-REVOCATION.md": _pack_revocation(),
        ROOT / "RECOVERY-RUNBOOK.md": _recovery_runbook(),
        ROOT / "RELEASE-RUNBOOK.md": _release_runbook(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    failures = 0
    for path, expected in render_docs().items():
        expected = expected if expected.endswith("\n") else expected + "\n"
        if args.check:
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != expected:
                failures += 1
                diff = difflib.unified_diff(
                    actual.splitlines(),
                    expected.splitlines(),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                    lineterm="",
                )
                sys.stdout.write("\n".join(diff) + "\n")
        else:
            path.write_text(expected, encoding="utf-8")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
