#!/usr/bin/env python3
"""Generate the V3.7 CapabilityTruthLedger documentation view."""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from srl.capabilities.truth import build_truth_ledger  # noqa: E402


def render() -> str:
    ledger = build_truth_ledger()
    rows = [
        "| Component | Family | Stage | State | Evidence axis |",
        "|---|---|---|---|---|",
    ]
    for item in ledger["components"]:
        rows.append(
            "| `{component}` | `{family}` | `{stage}` | `{state}` | `{axis}` |".format(
                component=item["component_id"],
                family=item["capability_family"],
                stage=item["activation_stage"],
                state=item["state"],
                axis=item["evidence_axis"],
            )
        )
    lines = [
        "# CAPABILITY-TRUTH-LEDGER",
        "",
        "<!-- generated by scripts/docs/generate_capability_truth_ledger.py; "
        "edit src/srl/capabilities/truth.py -->",
        "",
        "Machine source: `src/srl/capabilities/truth.py`.",
        "",
        "The V3.7 closure chain is:",
        "",
        "`DECLARED -> CONFIGURED -> INSTALLED -> EXECUTABLE_PROBED -> "
        "SCIENTIFIC_SMOKE_PASSED -> CROSSCHECKED -> ACTIVE`.",
        "",
        "Fixture-only, policy-only, adapter-only and executable-probe-only evidence",
        "cannot close `DONE` for `v2.0.0`.",
        "",
        "Current v1.0.1 active inventory reproduced by the ledger:",
        "",
        ", ".join(f"`{item}`" for item in ledger["current_v101_active_inventory_observed"]),
        "",
        *rows,
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    path = ROOT / "CAPABILITY-TRUTH-LEDGER.md"
    expected = render()
    expected = expected if expected.endswith("\n") else expected + "\n"
    if args.check:
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            diff = difflib.unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=str(path),
                tofile=f"{path} (generated)",
                lineterm="",
            )
            sys.stdout.write("\n".join(diff) + "\n")
            return 1
        return 0
    path.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
